### ISSUE TITLE
Add performance cops

### ISSUE THREAD

**Issue by klappradla** [bitcrowd/rubocop-bitcrowd#23]
The [`Cop::Performance`](https://www.rubydoc.info/gems/rubocop/0.67.1/RuboCop/Cop/Performance) cops [have been extracted](https://github.com/rubocop-hq/rubocop/blob/2c82b01ab60e4fb5d999ecd06fed057a311a6598/CHANGELOG.md#changes-3) from Rubocop's core into a standalone gem: https://github.com/rubocop-hq/rubocop-performance

These cops are MRI dependent and differ based on the Ruby version one is using.

Still, I think they could make a good addition to our configuration 🤔 

What do you think?

**Comment by andreasknoepfle** [comment]
awesome idea 👍 
We could just add a section that we recommend adding the extra cops in our README as a start, so it is still possible to opt out.

Or are there any things where you would overwrite configuration from those Cops? If so, maybe we can have a similar opt-in behaviour like with `rubocop-rspec`, so we create a `rubocop-performance.yml` in the repo to keep those.

**Comment by klappradla** [comment]
As they used to be part of the core and we did not yet have any special rules related to them _(at least searching for `performance` here on Github does not yield any results for me)_ we for starters probably wouldn't override anything.

**Comment by andreasknoepfle** [comment]
Also the rails cops seem to be separated soon: 
https://github.com/rubocop-hq/rubocop-rails

There is a post on that one as well:
https://metaredux.com/posts/2019/05/22/a-modular-rubocop.html

**Comment by klappradla** [comment]
Closed via #32
