### ISSUE TITLE
Warning unrecognized cop Layout/SpaceInsideBrackets

### ISSUE THREAD

**Issue by xhr15** [bitcrowd/rubocop-bitcrowd#5]
Warning: unrecognized cop Layout/SpaceInsideBrackets found in .../gems/rubocop-bitcrowd-1.1.2/.rubocop.yml
Warning: unrecognized cop Layout/SpaceInsideBrackets found in .rubocop.yml

**Comment by andreasknoepfle** [comment]
Sounds like a version issue. Which versions of rubocop are you using?

**Comment by paulodiniz** [comment]
The issue is caused by the deprecation of the `Layout/SpaceInsideBrackets` cop to two new cops
* `Layout/SpaceInsideArrayLiteralBrackets`
* `Layout/SpaceInsideReferenceBrackets`

There is PR which fixes this https://github.com/bitcrowd/rubocop-bitcrowd/pull/6
